import { Dimensions, StyleSheet } from "react-native";
const screenWidth = Dimensions.get("window").width;
const screenHeight = Dimensions.get("window").height;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1d1d1d",
    paddingHorizontal: 16,
    paddingTop: 40,
  },
  searchContainer: {
    marginBottom: 20,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 29,
  },
  header: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 12,
  },
  filtersScroll: {
    marginBottom: 18,
    flexGrow: 0,
    height: 46,
    maxHeight: 46,
  },
  filtersContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingRight: 8,
    paddingVertical: 4,
  },
  filterChip: {
    backgroundColor: "#2a2a2a",
    borderWidth: 1,
    borderColor: "#444",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 6,
    minHeight: 34,
    justifyContent: "center",
    alignItems: "center",
  },
  filterChipActive: {
    backgroundColor: "#FFC107",
    borderColor: "#FFC107",
  },
  filterChipText: {
    color: "#d4d4d4",
    fontSize: 13,
    fontWeight: "600",
  },
  filterChipTextActive: {
    color: "#1d1d1d",
  },
  servicesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  serviceCard: {
    width: screenWidth * 0.44,
    height: screenHeight * 0.22,
    backgroundColor: "#f0f0f0",
    borderRadius: 20,
    marginBottom: 16,
    overflow: "hidden",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "transparent",
  },
  selectedServiceCard: {
    borderColor: "#FFC107",
  },
  serviceIconWrap: {
    height: screenHeight * 0.15,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  serviceImage: {
    width: screenWidth * 0.22,
    height: screenWidth * 0.22,
    opacity: 1,
  },
  serviceTextWrap: {
    width: "100%",
    backgroundColor: "#1d1d1d",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    alignItems: "center",
  },
  serviceText: {
    color: "#ffffff",
    fontSize: screenWidth * 0.036,
    fontWeight: "700",
    textAlign: "center",
  },
  buttonContainer: {
    backgroundColor: "#FFC107",
    width: "80%",
    paddingVertical: 10,
    borderRadius: 24,
    marginTop: 20,
    alignSelf: "center",
  },
  findServicesText: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    color: "#3B3B3B",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingTop: 80,
  },
  emptyTitle: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
  },
  emptyText: {
    color: "#888",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
});